# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# <https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file>

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "hello-websocket-java/hello-websocket-common"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "maven"
    directory: "hello-websocket-java/hello-websocket-netty"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "maven"
    directory: "hello-websocket-java/hello-websocket-springboot"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "gomod"
    directory: "hello-websocket-go"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "cargo"
    directory: "hello-websocket-rust"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "npm"
    directory: "hello-websocket-nodejs"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "pub"
    directory: "hello-websocket-flutter-client"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Shanghai"