spring.main.banner-mode: off
logging:
  level:
    root: INFO
#    org.springframework.web.socket: TRACE
#    org.springframework.messaging.simp: TRACE
server:
  port: 8080
  shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s