version: "3.8"

services:
  ws-server-swift:
    image: feuyeux/ws_server_swift:1.0.0
    ports:
      - "9898:9898"
    networks:
      - ws_network

  ws-client-swift:
    image: feuyeux/ws_client_swift:1.0.0
    environment:
      - WS_SERVER=ws-server-swift
      - WS_PORT=9898
    depends_on:
      - ws-server-swift
    networks:
      - ws_network

networks:
  ws_network:
    driver: bridge
