version: "3.8"

services:
  ws-server-php:
    image: feuyeux/ws_server_php:1.0.0
    ports:
      - "9898:9898"
    networks:
      - ws_network

  ws-client-php:
    image: feuyeux/ws_client_php:1.0.0
    environment:
      - WS_SERVER=ws-server-php
      - WS_PORT=9898
    depends_on:
      - ws-server-php
    networks:
      - ws_network

networks:
  ws_network:
    driver: bridge
