version: "3.8"

services:
  ws-server-java:
    image: feuyeux/ws_server_java:1.0.0
    ports:
      - "9898:9898"
    networks:
      - ws_network

  ws-client-go:
    image: feuyeux/ws_client_go:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-rust:
    image: feuyeux/ws_client_rust:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-cpp:
    image: feuyeux/ws_client_cpp:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-csharp:
    image: feuyeux/ws_client_csharp:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-python:
    image: feuyeux/ws_client_python:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-node:
    image: feuyeux/ws_client_node:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-dart:
    image: feuyeux/ws_client_dart:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-kotlin:
    image: feuyeux/ws_client_kotlin:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-swift:
    image: feuyeux/ws_client_swift:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-php:
    image: feuyeux/ws_client_php:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

  ws-client-ts:
    image: feuyeux/ws_client_ts:1.0.0
    environment:
      - WS_SERVER=ws-server-java
      - WS_PORT=9898
    depends_on:
      - ws-server-java
    networks:
      - ws_network

networks:
  ws_network:
    driver: bridge
