name: Building

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Rust
      run: cargo build --manifest-path hello-websocket-rust/Cargo.toml 
    - name: Run Rust tests
      run: cargo test --manifest-path hello-websocket-rust/Cargo.toml --verbose
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build server with Maven
      run: mvn -B package --file hello-websocket-java/springboot/server/pom.xml
    - name: Build client with Maven
      run: mvn -B package --file hello-websocket-java/springboot/client/pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}